// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ZoVvNZGk7DpSp1QuwkX8vwd52dn1zjI',
    appId: '1:16792938699:web:5d45e714608a0ea241534e',
    messagingSenderId: '16792938699',
    projectId: 'whats-app-backend-a0eee',
    authDomain: 'whats-app-backend-a0eee.firebaseapp.com',
    storageBucket: 'whats-app-backend-a0eee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxc7b_le9Zwq8Hx1v8VjotjYE9Cn5RE6A',
    appId: '1:16792938699:android:d7f0738f1e7ec09b41534e',
    messagingSenderId: '16792938699',
    projectId: 'whats-app-backend-a0eee',
    storageBucket: 'whats-app-backend-a0eee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOG1Qrvzr723_oDj21u7n920BBR1yXtfY',
    appId: '1:16792938699:ios:8acb7383eabedefc41534e',
    messagingSenderId: '16792938699',
    projectId: 'whats-app-backend-a0eee',
    storageBucket: 'whats-app-backend-a0eee.appspot.com',
    iosClientId: '16792938699-0q0kfus679igao4kduksj7lp3npu460i.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOG1Qrvzr723_oDj21u7n920BBR1yXtfY',
    appId: '1:16792938699:ios:84d2deb385c1089f41534e',
    messagingSenderId: '16792938699',
    projectId: 'whats-app-backend-a0eee',
    storageBucket: 'whats-app-backend-a0eee.appspot.com',
    iosClientId: '16792938699-5elbg5vopstdq97e7hjkpnk5544f9pkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
